# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

r1 = Role.create({name: "Student", description: "Can read items"})
r2 = Role.create({name: "Instructor", description: "Can read and create items. Can update and destroy own items"})
r3 = Role.create({name: "Admin", description: "Can perform any CRUD operation on any resource"})
 
u1 = User.create({email: "sally@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r1.id})
u2 = User.create({email: "sue@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r2.id})
u3 = User.create({email: "kev@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r2.id})
u4 = User.create({email: "jack@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r3.id})
u5 = User.create({email: "student@uiowa.edu", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r1.id})
u6 = User.create({email: "instructor@uiowa.edu", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r2.id})
u7 = User.create({email: "admin@uiowa.edu", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r3.id})

c1 = College.create({name: "College of Engineering"})
c2 = College.create({name: "Tippie College of Business"})
c3 = College.create({name: "College of Liberal Arts and Science"})

d1 = Department.create({name: "ECE", number: 55})
d2 = Department.create({name: "CS", number: 22})
d3 = Department.create({name: "Art", number: 1})
d4 = Department.create({name: "Math", number: 22})
d5 = Department.create({name: "Astronomy", number: 29})
d6 = Department.create({name: "Athletic Training", number: 27})
d7 = Department.create({name: "BME", number: 51})
d8 = Department.create({name: "Chemistry", number: 4})

co1 = Course.create({name: "Database Systems", location: "MLH", number: 4400, section: 0001, enrollment: 20, maxenrollment: 20, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project, Database Minute", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co2 = Course.create({name: "Engineering Math 3: Matrix Algebra", location: "BCSB", number: 2550, section: 0121, enrollment: 13, maxenrollment: 60, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co3 = Course.create({name: "Engineering Math 3: Matrix Algebra", location: "MLH", number: 2550, section: 0001, enrollment: 100, maxenrollment: 100, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co4 = Course.create({name: "Engineering Math 5: Vector Calculus", location: "MLH", number: 3550, section: 0102, enrollment: 34, maxenrollment: 34, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co5 = Course.create({name: "Engineering Math 5: Vector Calculus", location: "MLH", number: 3550, section: 0121, enrollment: 34, maxenrollment: 34, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co6 = Course.create({name: "Engineering Math 5: Vector Calculus", location: "MLH", number: 3550, section: 0122, enrollment: 13, maxenrollment: 34, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co7 = Course.create({name: "Engineering Math 5: Vector Calculus", location: "MLH", number: 3550, section: 0231, enrollment: 22, maxenrollment: 34, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co8 = Course.create({name: "Elementary Numerical Anylsis", location: "MLH", number: 3700, section: 0001, enrollment: 32, maxenrollment: 32, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co9 = Course.create({name: "Elementary Numerical Anylsis", location: "MLH", number: 3700, section: 0002, enrollment: 25, maxenrollment: 32, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co10 = Course.create({name: "Computer Science II: Data Structures", location: "SH", number: 2230, section: 0001, enrollment: 94, maxenrollment: 96, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co11 = Course.create({name: "Topics in Computer Science II", location: "AJB", number: 4980, section: 0001, enrollment: 17, maxenrollment: 30, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co12 = Course.create({name: "Engineering Problem Solving II", location: "SC", number: 1300, section: 0001, enrollment: 5, maxenrollment: 70, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co14 = Course.create({name: "Engineering Problem Solving II", location: "SC", number: 1300, section: 0002, enrollment: 11, maxenrollment: 70, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co15 = Course.create({name: "Engineering Problem Solving II", location: "SC", number: 1300, section: 0003, enrollment: 13, maxenrollment: 70, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co16 = Course.create({name: "Engineering Problem Solving II", location: "SC", number: 1300, section: 0004, enrollment: 3, maxenrollment: 70, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co17 = Course.create({name: "Computers in Engineering", location: "SC", number: 2730, section: 0001, enrollment: 43, maxenrollment: 68, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )
co18 = Course.create({name: "Intro to Software Design", location: "SC", number: 3330, section: 0001, enrollment: 49, maxenrollment: 58, dropbox:"Homework 1, Homework 2, Homework 3, Homework 4, Group Project", news: "Homework 4 Clarification: I set a deadline before which questions need to be asked.  The reason is to avoid undue advantage to some one who would ask a good question but on the HW due date. With last minute questions, I run the risk of not having the time to give clarifications to all or  completely miss answering a question  because it is too late. Anyway here is a clrification on Q#1 for all students : Conceptual Analysis, Logical Design, Physical design ahs been dealt in detail in Lectures. Conceptual Analysis - ER diagram which you drew in HW3 - Use that if it is correct   and  with that derive the Logical Design  and Physical design as explained in lectures.Thanks for helping me follow the process.", quiz: "There will be a quiz over Chapter 2 on Tuesday.", coursetype: 1} )


b1 = Book.create({title: "Harry Potter", author: "J.K. Rowling", publisher: "Harper Collins", location: "Main Library", details:"A boy finds out he's a wizard."})
b2 = Book.create({title: "Analysis and Design of Integrated Circuits", author: "K.C. Gupta", publisher: "Wiley", location: "Engineering Library", details:"A boy finds out he's a wizard."})
b3 = Book.create({title: "After", author: "Amy Efaw", publisher: "Viking Juvenile", location: "Main Library", details:"A boy finds out he's a wizard."})
b4 = Book.create({title: "Battle Dress", author: "Amy Efaw", publisher: "Harper Teen", location: "Main Library", details:"A boy finds out he's a wizard."})
b5 = Book.create({title: "Client Server Information Systems", author: "J.E. Goldman", publisher: "John Wiley & Sons Inc.", location: "Engineering Library", details:"A boy finds out he's a wizard."})
b6 = Book.create({title: "Soccer 100", author: "Ali Ncana", publisher: "Ibbotson", location: "Main Library", details:"A boy finds out he's a wizard."})
b7 = Book.create({title: "Digital Design from Zero to One", author: "J.D. Daniels", publisher: "John Wiley & Sons Inc.", location: "Engineering Library", details:"A boy finds out he's a wizard."})











